version: '3.8'
services:
  db:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mengede_dev
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
